### ISSUE TITLE
Module Status Inquiry

### ISSUE THREAD

**Issue by Norc** [strass/foundry-progressclocks#11]
Hello, there's been a lot of interest in this module recently even though it was never released. I tested it in 0.7.5 and it seems to be working beautifully.

Anyway, i had two questions:

1) I was wondering what your plans were for this... do you have any intention of finishing this off and releasing it?
2) Would you mind if someone else adopted your excellent work and released it to the Foundry community to use?

**Comment by Norc** [comment]
Feel free to ping me on Foundry Discord, Norc'thulhu#5108. Thanks!

**Comment by strass** [comment]
I don't currently have any plans, I haven't transferred my games to Foundry so I don't have enough motivation to keep working on this module. Anyone is free to submit pull requests or fork the repo with recognition

**Comment by Norc** [comment]
Thanks for the answer, and good luck with everything.
